openapi: 3.0.0
info:
  title: YouTube Multi API
  description: API for downloading YouTube videos as MP3/MP4 and getting AI-processed transcripts
  version: 1.0.0
  contact:
    name: BaySercan
    url: https://github.com/BaySercan/youtube-multi-api
servers:
  - url: http://localhost:3500
    description: Local development server
  - url: https://p01--youtube-multi-api-private-srv--yfb9ttcdx8bx.code.run
    description: Production server (Private Service)
    
security:
  - BearerAuth: []
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    VideoInfoSummary:
      type: object
      properties:
        availability:
          type: string
          nullable: true
        automatic_captions:
          type: object
        categories:
          type: array
          items:
            type: string
        channel_name: # Changed from channel
          type: string
        channel_follower_count:
          type: integer
          nullable: true
        channel_id:
          type: string
        channel_url:
          type: string
        comment_count:
          type: integer
          nullable: true
        description:
          type: string
        display_id:
          type: string
        duration:
          type: integer
        duration_string:
          type: string
        filesize_approx:
          type: integer
          nullable: true
        fulltitle:
          type: string
        video_id: # Changed from id
          type: string
        language:
          type: string
          nullable: true
        license:
          type: string
          nullable: true
        like_count:
          type: integer
          nullable: true
        original_url:
          type: string
        playable_in_embed:
          type: boolean
          nullable: true
        tags:
          type: array
          items:
            type: string
        thumbnail:
          type: string
        timestamp:
          type: integer
          nullable: true
        title:
          type: string
        post_date: # Added post_date, upload_date removed from summary schema
          type: string
          format: date-time
        uploader:
          type: string
        uploader_id:
          type: string
          nullable: true
        uploader_url:
          type: string
          nullable: true
        view_count:
          type: integer
          nullable: true
        was_live:
          type: boolean
          nullable: true
    VideoInfoFull:
      type: object
      description: Represents the full video information object. The properties can vary.
      # As the full object can be very diverse and large,
      # we define it as a generic object or you can list known common properties.
      # For simplicity, marking as a generic object:
      additionalProperties: true
paths:
  /ping:
    get:
      summary: Health check endpoint
      description: No authentication required
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-06-01T16:00:00.000Z"
                  version:
                    type: string
                    example: "1.0.0"
  /info:
    get:
      summary: Get video metadata
      description: Retrieve metadata about a YouTube video
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: YouTube video URL
        - in: query
          name: type
          required: false
          schema:
            type: string
            enum:
              - sum
              - full
            default: sum
          description: Type of information to return (sum for summary, full for all details)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                oneOf: # Indicates that the response can be one of the following schemas
                  - $ref: '#/components/schemas/VideoInfoSummary'
                  - $ref: '#/components/schemas/VideoInfoFull'
              examples:
                summary:
                  value:
                    availability: null
                    automatic_captions: {}
                    categories: ["Music"]
                    channel_name: "Official Channel" # Changed
                    channel_follower_count: 1000000
                    channel_id: "UC12345678"
                    channel_url: "https://www.youtube.com/channel/UC12345678"
                    comment_count: 5000
                    description: "Video description text."
                    display_id: "dQw4w9WgXcQ"
                    duration: 212
                    duration_string: "3:32"
                    filesize_approx: 5000000
                    fulltitle: "Full Video Title"
                    video_id: "dQw4w9WgXcQ" # Changed
                    language: "en"
                    license: "Standard YouTube License"
                    like_count: 100000
                    original_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                    playable_in_embed: true
                    tags: ["tag1", "tag2"]
                    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg"
                    timestamp: 1254000000
                    title: "Video Title"
                    post_date: "2009-10-25T00:00:00.000Z" # Changed from upload_date and format updated
                    uploader: "Uploader Name"
                    uploader_id: "uploaderID"
                    uploader_url: "https://www.youtube.com/user/uploaderID"
                    view_count: 100000000
                    was_live: false
                full:
                  description: "Full video information, structure may vary."
                  value: {
                    "id": "dQw4w9WgXcQ",
                    "title": "Video Title",
                    "formats": [],
                    "thumbnails": [],
                    "description": "Video description text.",
                    "upload_date": "20091025",
                    "uploader": "Uploader Name",
                    "uploader_id": "uploaderID",
                    "uploader_url": "https://www.youtube.com/user/uploaderID",
                    "channel_id": "UC12345678",
                    "channel_url": "https://www.youtube.com/channel/UC12345678",
                    "duration": 212,
                    "view_count": 100000000,
                    "average_rating": null,
                    "age_limit": 0,
                    "webpage_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    "categories": ["Music"],
                    "tags": ["tag1", "tag2"],
                    "playable_in_embed": true,
                    "live_status": "not_live",
                    "release_timestamp": null,
                    "_format_sort_fields": ["fps", "res", "tbr", "format_id"],
                    "automatic_captions": {},
                    "subtitles": {},
                    "comment_count": 5000,
                    "chapters": null,
                    "heatmap": null,
                    "like_count": 100000,
                    "channel": "Official Channel",
                    "channel_follower_count": 1000000,
                    "track": "Track Title",
                    "artist": "Artist Name",
                    "album": "Album Name",
                    "release_date": null,
                    "release_year": null,
                    "webpage_url_basename": "watch?v=dQw4w9WgXcQ",
                    "webpage_url_domain": "youtube.com",
                    "extractor": "youtube",
                    "extractor_key": "Youtube",
                    "playlist": null,
                    "playlist_index": null,
                    "thumbnail": "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
                    "display_id": "dQw4w9WgXcQ",
                    "requested_subtitles": null,
                    "_has_drm": null,
                    "fulltitle": "Full Video Title",
                    "duration_string": "3:32",
                    "epoch": 1672531200,
                    "original_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    "filename": "video.mp4",
                    "_filename": "video.mp4",
                    "filesize_approx": 5000000,
                    "was_live": false,
                    "availability": "public",
                    "language": "en",
                    "license": "Standard YouTube License",
                    "timestamp": 1254000000
                  }
        '400':
          description: Invalid request
  /mp3:
    get:
      summary: Download video as MP3
      description: Download a YouTube video as an MP3 audio file
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: YouTube video URL
      responses:
        '200':
          description: MP3 file download
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request
  /mp4:
    get:
      summary: Download video as MP4
      description: Download a YouTube video as an MP4 video file
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: YouTube video URL
      responses:
        '200':
          description: MP4 file download
          content:
            video/mp4:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request
  /transcript:
    get:
      summary: Get video transcript
      description: Retrieve AI-processed video transcript
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: YouTube video URL
        - in: query
          name: lang
          schema:
            type: string
            default: tr
          description: Language code (e.g., en, tr, es)
        - in: query
          name: skipAI
          schema:
            type: boolean
            default: false
          description: Skip AI processing
        - in: query
          name: useDeepSeek
          schema:
            type: boolean
            default: true
          description: Use DeepSeek model for processing
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  title:
                    type: string
                  language:
                    type: string
                  transcript:
                    type: string
                  ai_notes:
                    type: string
                  isProcessed:
                    type: boolean
                  processor:
                    type: string
                  video_id:
                    type: string
                  channel_id:
                    type: string
                  channel_name:
                    type: string
                  post_date:
                    type: string
              example:
                success: true
                title: "Example Video Title"
                language: "tr"
                transcript: "This is the cleaned transcript text..."
                ai_notes: "Processing notes from AI model"
                isProcessed: true
                processor: "deepseek"
                video_id: "dQw4w9WgXcQ"
                channel_id: "UC12345678"
                channel_name: "Example Channel"
                post_date: "20230101"
        '400':
          description: Invalid request or no subtitles available
          
  /progress/{id}:
    get:
      summary: Get processing status
      description: Retrieve the current status of a processing job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Processing job ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                  progress:
                    type: number
                  video_id:
                    type: string
                  video_title:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  lastUpdated:
                    type: string
                    format: date-time
        '404':
          description: Processing ID not found
          
  /result/{id}:
    get:
      summary: Get processing result
      description: Retrieve the final result of a completed processing job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Processing job ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  title:
                    type: string
                  language:
                    type: string
                  transcript:
                    type: string
                  ai_notes:
                    type: string
                  isProcessed:
                    type: boolean
                  processor:
                    type: string
                  video_id:
                    type: string
                  channel_id:
                    type: string
                  channel_name:
                    type: string
                  post_date:
                    type: string
        '202':
          description: Processing not complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                  progress:
                    type: number
        '404':
          description: Processing ID not found
  /cancel/{id}:
    post:
      summary: Cancel a processing job
      description: Cancel a running processing job (MP3, MP4, or transcript)
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Processing job ID
      responses:
        '200':
          description: Successful cancellation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  video_id:
                    type: string
                    nullable: true
                    description: ID of the video being processed
                  video_title:
                    type: string
                    nullable: true
                    description: Title of the video being processed
                  queue_position:
                    type: string
                    nullable: true
                    description: Position in queue if job was waiting (e.g., "Was #3 in queue")
              example:
                message: "Process canceled successfully"
                video_id: "dQw4w9WgXcQ"
                video_title: "Example Video Title"
                queue_position: "Was #2 in queue"
        '400':
          description: Process cannot be canceled or is already complete
        '404':
          description: Processing ID not found
